### ISSUE TITLE
add support go 1.17.x

### ISSUE THREAD

**Issue by vay3t** [alitto/pond#15]
I have tried to download the module using go get URL, but I have not been able to, I suspect that the version of go 1.17.2 that is the one I currently occupy is placing a restriction for something that the repository is missing.

**Comment by alitto** [comment]
Hey @vay3t! could you provide the logs you are getting when running `go get github.com/alitto/pond`?

I tried it and it seems to be working with go 1.17.3, here's what I'm seeing:

```bash
$ go version
go version go1.17.3 linux/amd64

$ go get github.com/alitto/pond
go: downloading github.com/alitto/pond v1.5.1
go get: added github.com/alitto/pond v1.5.1
```

Thanks!

**Comment by vay3t** [comment]
# go version
![image](https://user-images.githubusercontent.com/6080369/142730009-9da350f3-7f9a-443a-a6db-ea91ca36704e.png)

# problem with clone
strangely I do not create the directory of the library, but I installed a library recently and it installed correctly. do you know of any necessary configuration?
![image](https://user-images.githubusercontent.com/6080369/142729936-152f2248-1a53-4164-ba43-719608549418.png)

# my env
![image](https://user-images.githubusercontent.com/6080369/142730004-fe479df4-e323-4585-a606-9f117440b1ee.png)

**Comment by alitto** [comment]
Ahh I think I know what's going on. Since this library uses [Go modules](https://go.dev/blog/using-go-modules), its source code is downloaded to a different directory, not to `go/src` but `go/pkg/mod`.
Could you check whether it's in that directory? E.g.: `ls ~/go/pkg/mod/github.com/alitto/`

**Comment by vay3t** [comment]
it does exist.
![image](https://user-images.githubusercontent.com/6080369/142730563-8c13ef67-c473-4101-ac7d-3886e70b683d.png)

that is if it is not possible to import.
![image](https://user-images.githubusercontent.com/6080369/142730631-322e0497-a652-4684-9455-788aba66c86f.png)

**Comment by alitto** [comment]
Could you show me the contents of `/home/vay3t/dev/multithread-go/go.mod`? That file defines the name of the module you are developing and it seems it has the same name as the pond library `github.com/alitto/pond`. You could try changing it to something like `github.com/vay3t/multithread-go`

**Comment by vay3t** [comment]
I greatly appreciate your help :)

look i got this
![image](https://user-images.githubusercontent.com/6080369/142731460-124e9ef3-5b37-4334-bbad-31cb8bc9762a.png)

file: 
![image](https://user-images.githubusercontent.com/6080369/142731520-b1be257c-f24d-4d70-9f4f-acde033eb981.png)

**Comment by alitto** [comment]
Ahh I think that's due to the name of the module in `go.mod`, please change that file to have this content:
```go
module github.com/vay3t/multithread-go

go 1.17
```

**Comment by vay3t** [comment]
i installed module with go get and logs:
![image](https://user-images.githubusercontent.com/6080369/142738564-4c04a2cc-a382-4593-92ec-5dc8b4df2a67.png)

a solution was to download the module with git clone, place it in the corresponding directory and run the example from there, which works without problems:
![image](https://user-images.githubusercontent.com/6080369/142737972-7f3ef796-b032-47c5-bdae-dcc5867fe7b0.png)

but when I try to import from an external repository I get the following error
![image](https://user-images.githubusercontent.com/6080369/142738887-6c257642-596f-4ef0-806e-640762dd93b4.png)

my code:
![image](https://user-images.githubusercontent.com/6080369/142738968-d23b43a0-90b4-480a-a731-e39eb90429c2.png)

**Comment by alitto** [comment]
You'll need to change the contents of the file `/home/vay3t/dev/multithread-go/go.mod` to be:
```
module github.com/vay3t/multithread-go

go 1.17
```

To give more context, when you create a `go.mod` file under the `multithread-go` directory, you are effectively creating a new Go module there, so all `*.go` files within that directory (such as main.go) will be part of this new module. The first line in the `go.mod` defines the absolute name of your module (`module {module-name}`), which cannot be the same as one of its dependencies, because that would mean there's a module that depends on itself (an import cycle, as the error message prints out). So the solution is to change the module name to something other than `github.com/alitto/pond` :slightly_smiling_face:

**Comment by vay3t** [comment]
I understood everything. I was able to fix the problem. Sorry for the time I made you waste.

Fixed

**Comment by alitto** [comment]
I'm glad the issue is fixed :+1: . No worries! thanks to you for using the lib :slightly_smiling_face:
