### ISSUE TITLE
Feature request: Add "Join" functionality to the group

### ISSUE THREAD

**Issue by opengs** [alitto/pond#59]
## Problem
I am running an application that consistently operates with a specific number of workers. Additionally, when a worker discovers work, it requires a boost from the pool. To achieve this, a limited shared pool for boosting is necessary.

## Proposed Feature
The idea is to introduce a Join functionality to the Group, enabling the current goroutine not only to wait for all tasks in the group to complete but also to assist in executing the tasks within it. So the general flow is:
- When a goroutine calls `Join` on a Group, it becomes part of the execution pool for that group.
- The goroutine waits for all tasks within the group to finish, actively participating in executing these tasks rather than idly waiting.

## Example

```golang
package main

import (
	"fmt"

	"github.com/alitto/pond"
)

func main() {

	// Create a pool
	pool := pond.New(10, 1000)
	defer pool.StopAndWait()

	// Create a task group
	group := pool.Group()

	// Submit a group of tasks
	for i := 0; i < 20; i++ {
		n := i
		group.Submit(func() {
			fmt.Printf("Running group task #%d\n", n)
		})
	}

	// Join pool for this group and help for all tasks in the group to complete
	group.Join()
}
```

## Other
Maybe for consistency this functionality also should be added to the `WorkerPool` object itself, but I cant imagine situation where it can be needed.

**Comment by opengs** [comment]
I think ability to limit the size of the `WorkGroup` can also solve the problem

**Comment by alitto** [comment]
Hey @opengs!

v2 of `pond` was released and it introduces a new feature called ["Subpools"](https://github.com/alitto/pond?tab=readme-ov-file#subpools-v2) which might be useful in this particular situation. The core idea is each pool can have sub-pools which have a fraction of the maximum concurrency of the main pool.

```go
// Create a pool that can run up to 10 goroutines concurrently
pool := pond.NewPool(10)

// Create a subpool with a fraction of the parent pool's concurrency
subpool := pool.NewSubpool(2)

// Submit a task to the subpool
subpool.Submit(func() {
	fmt.Println("Running task in subpool")
})
``` 

In the example above, both `pool` and `subpool` share a global limit of 10 goroutines, but tasks submitted to `subpool` will run with a lower limit (2). I imagine this could be useful if you have to invoke an expensive API that is rate-limited and you want to provide enhanced rate to a subset of your clients (e.g. premium users can have a higher concurrency than freemium ones).

This new "Subpools" feature was heavily inspired in this Issue so thanks for opening it! Please let me know your thoughts about this :slightly_smiling_face:
