### ISSUE TITLE
group: panic when submitting zero tasks

### ISSUE THREAD

**Issue by mastercactapus** [alitto/pond#78]
This behavior seems to be intentional, so I'm curious if there's an implementation reason why this isn't allowed?

Here's an example:
```go
var tasks []func() Rule
for _, rule := range matchingRules {
	if rule.Disabled {
		continue
	}
	tasks = append(tasks, func() Rule {
		return lookupRule(ctx, rule, body)
	})
}

// panic if len(tasks) == 0, rather than returning `nil, nil`
return ruleLookupPool.NewGroup().Submit(tasks...).Wait()
```

It's easy enough to do a length check first but it was a bit unexpected -- I expected to get an empty slice back.

---

That said, I'm guessing the expected pattern is to call `Submit` multiple times _instead_ and will update my code as such -- but thought I'd raise the issue in case there's any additional context around it.

**Comment by alitto** [comment]
Hey @mastercactapus, thanks for bringing this up!

I agree the panic in this situation is a bit unexpected. I opened a PR to remove the panic and return an empty slice + a `nil` error in this case. This fix is released in https://github.com/alitto/pond/releases/tag/v2.0.4

Cheers!
